#!/usr/bin/env python3
"""Regenerate the frontend contract files in schemas/ from the live implementation.

Writes only schemas/aqualens-{openapi,product.schema,demo-examples}.json. Uses a throwaway runtime
directory, so no runtime, frozen or research artifact is read for writing or modified.

Run: PYTHONPATH=packages .venv/bin/python scripts/export_product_contracts.py [--check]
"""
from __future__ import annotations

import argparse
import json
import os
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'schemas'


def product_schema() -> dict:
    from sagar.api import product_models as m
    names = ['ProductMission', 'MissionInput', 'UploadRecord', 'SurveyView', 'Contact', 'Evidence', 'Machine',
             'Analyst', 'ReviewInput', 'ClassificationInput', 'PriorityInput', 'NoteInput', 'ReviewEvent',
             'Capability', 'MapResponse', 'MissionReport']
    return {'$comment': 'Generated by scripts/export_product_contracts.py; do not edit by hand.',
            'models': {name: getattr(m, name).model_json_schema() for name in names}}


def build() -> dict[str, dict]:
    with tempfile.TemporaryDirectory() as runtime:
        os.environ['SAGARDRISHTI_RUNTIME_DIR'] = runtime
        os.environ['AQUALENS_DEMO_MODE'] = '1'
        from fastapi.testclient import TestClient
        from sagar.api import create_app
        app = create_app(ROOT)
        client = TestClient(app)
        mission = client.post('/api/v1/demo/seed').json()
        mid = mission['mission_id']
        examples = {
            '$comment': 'Deterministic DEMO fixture responses. Every object is demo=true / SYNTHETIC_DEMO; not scientific output.',
            'GET /api/v1/missions/{demo_mission_id}': client.get(f'/api/v1/missions/{mid}').json(),
            'GET /api/v1/missions/{id}/surveys': client.get(f'/api/v1/missions/{mid}/surveys').json(),
            'GET /api/v1/missions/{id}/contacts': client.get(f'/api/v1/missions/{mid}/contacts').json(),
            'GET /api/v1/contacts/demo_contact_a (known target: machine CRAB_POT, UNREVIEWED at seed)':
                client.get('/api/v1/contacts/demo_contact_a').json(),
            'GET /api/v1/contacts/demo_contact_b (no machine class, local anomaly NOT_VALIDATED, UNREVIEWED at seed)':
                client.get('/api/v1/contacts/demo_contact_b').json(),
            'GET /api/v1/contacts/{id}/history (demo_contact_c, one scripted verdict)': client.get('/api/v1/contacts/demo_contact_c/history').json(),
            'GET /api/v1/missions/{id}/map': client.get(f'/api/v1/missions/{mid}/map').json(),
            'GET /api/v1/system/capabilities': client.get('/api/v1/system/capabilities').json(),
        }
        return {'aqualens-openapi.json': app.openapi(), 'aqualens-product.schema.json': product_schema(),
                'aqualens-demo-examples.json': examples}


def encode(value: dict) -> str:
    return json.dumps(value, indent=2, sort_keys=True, ensure_ascii=False) + '\n'


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true', help='fail if checked-in files differ')
    args = parser.parse_args()
    stale = []
    for name, value in build().items():
        path = OUT / name
        if args.check:
            if not path.is_file() or path.read_text() != encode(value):
                stale.append(name)
        else:
            path.write_text(encode(value))
            print(path.relative_to(ROOT))
    if stale:
        print('stale contract files: ' + ', '.join(stale), file=sys.stderr)
        return 1
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
